#!/bin/sh /etc/rc.common
# Start after the packaged uWSGI (79) and nginx (80) services.
START=81
STOP=19
USE_PROCD=1

start_service() {
	procd_open_instance
	procd_set_param command /usr/sbin/zbt-luci-backend-check
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param oneshot 1
	procd_close_instance
}
