#!/bin/sh
set -eu
if [ -x /etc/init.d/speedify-installer ]; then
	/etc/init.d/speedify-installer enable >/dev/null 2>&1 || true
	/etc/init.d/speedify-installer start >/dev/null 2>&1 || true
fi
exit 0
