FROM ubuntu:24.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext \
    git libncurses5-dev libssl-dev python3 python3-setuptools python3-pip rsync \
    swig unzip wget zlib1g-dev file xz-utils libelf-dev ecj fastjar java-propose-classpath \
    jq curl ca-certificates pkgconf ccache time && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
