#!/bin/sh
# Independent egress TTL policy. Never query AT, reset or redial a modem.
. /usr/lib/zbt/dual-modem.sh

zbt_ttl_valid() {
	case "$1" in ''|*[!0-9]*|0*|????*) return 1 ;; esac
	[ "$1" -ge 1 ] && [ "$1" -le 255 ]
}

zbt_ttl_any_enabled() {
	[ "$(uci -q get qmodem_ttl.4_1.enable)" = 1 ] ||
		[ "$(uci -q get qmodem_ttl.2_1.enable)" = 1 ]
}

zbt_ttl_recommend() {
	local address
	# Preserve the inherited passive 64/65 heuristic, but per physical modem.
	# This is not an AT query or a guarantee of a carrier's required value.
	address=$(ip -4 -o addr show dev "$1" scope global 2>/dev/null | awk '{print $4; exit}')
	case "$address" in
		192.0.0.*|192.168.225.*|10.168.*) printf '65\n' ;;
		*) printf '64\n' ;;
	esac
}

zbt_ttl_render() {
	local section ttl mode device index rules=''
	for section in 4_1 2_1; do
		[ "$(uci -q get "qmodem_ttl.$section.enable")" = 1 ] || continue
		mode=$(uci -q get "qmodem_ttl.$section.mode") || mode=manual
		ttl=$(uci -q get "qmodem_ttl.$section.ttl")
		case "$mode" in auto|manual) ;; *) return 1 ;; esac
		if [ "$mode" = manual ] && ! zbt_ttl_valid "$ttl"; then
			logger -t qmodem_ttl "Invalid TTL for $section; keeping the last applied rules"
			return 1
		fi
		# Resolve by USB slot, never by whichever wwanN happened to appear first.
		device=$(zbt_netdev "$section") || continue
		[ "$mode" != auto ] || ttl=$(zbt_ttl_recommend "$device")
		index=$(cat "${ZBT_SYSFS:-/sys}/class/net/$device/ifindex" 2>/dev/null) || continue
		case "$index" in ''|*[!0-9]*|0*|??????????*) return 1 ;; esac
		[ "$(zbt_netdev "$section")" = "$device" ] || continue
		# An ifindex stops matching when this device disappears. Reusing its
		# old name for the other modem cannot temporarily inherit its TTL.
		rules="$rules
	meta oif $index ip ttl set $ttl comment \"QModem $section IPv4\"
	meta oif $index ip6 hoplimit set $ttl comment \"QModem $section IPv6\""
	done
	printf '%s\n' '# Generated by zbt-qmodem-ttl; edit QModem -> TTL, not this RAM file.'
	[ -n "$rules" ] || return 0
	printf 'chain zbt_qmodem_ttl_postrouting {\n\ttype filter hook postrouting priority mangle; policy accept;%s\n}\n' "$rules"
}

# Recognize only the complete old firmware-generated primary-modem rule.
# Arbitrary additional rules are archived, not interpreted or executed.
zbt_ttl_legacy_primary() {
	local file="$1" content ttl expected
	[ -f "$file" ] || return 1
	content=$(sed '/^[[:space:]]*#/d; /^[[:space:]]*$/d; s/^[[:space:]]*//' "$file")
	ttl=$(printf '%s\n' "$content" | sed -n 's/^oifname "wwan0" ip ttl set \([0-9]*\)$/\1/p')
	zbt_ttl_valid "$ttl" || return 1
	expected=$(printf 'chain postrouting {\ntype filter hook postrouting priority mangle; policy accept;\noifname "wwan0" ip ttl set %s\noifname "wwan0" ip6 hoplimit set %s\n}' "$ttl" "$ttl")
	[ "$content" = "$expected" ] || return 1
	printf '%s\n' "$ttl"
}

zbt_ttl_migrate() {
	local etc="${ZBT_TTL_ETC:-/etc}" section key value legacy enable ttl mode schema changed=0 file backup
	legacy=$(zbt_ttl_legacy_primary "$etc/nftables.d/99-tether-ttl.nft") || legacy=''
	schema=$(uci -q get qmodem_ttl.main.schema) || schema=0
	# Schema 2 briefly seeded primary automatic TTL on. Correct only that exact
	# generated footprint so upgrades regain flow offload; preserve every custom
	# value, mode, secondary policy and subsequently edited configuration.
	if [ "$schema" = 2 ] &&
		[ "$(uci -q get qmodem_ttl.4_1.enable)" = 1 ] &&
		[ "$(uci -q get qmodem_ttl.4_1.ttl)" = 64 ] &&
		[ "$(uci -q get qmodem_ttl.4_1.mode)" = auto ] &&
		[ "$(uci -q get qmodem_ttl.2_1.enable)" = 0 ] &&
		[ "$(uci -q get qmodem_ttl.2_1.ttl)" = 64 ] &&
		[ "$(uci -q get qmodem_ttl.2_1.mode)" = auto ]; then
		uci set qmodem_ttl.4_1.enable=0 || return 1
		changed=1
	fi
	for section in 4_1 2_1; do
		# TTL rewriting disables flow offload, so both slots are opt-in on a
		# fresh installation. Preserve an explicitly enabled legacy plugin, but
		# do not mistake the old always-present wwan0 include for user consent.
		enable=0; ttl=64; mode=auto
		if [ "$schema" != 2 ] && [ "$schema" != 3 ]; then
			value=$(uci -q get qmodem_ttl.main.ttl)
			if [ "$(uci -q get qmodem_ttl.main.enable)" = 1 ] && zbt_ttl_valid "$value"; then
				# Preserve an explicit legacy global choice on both modems only.
				enable=1; ttl=$value; mode=manual
			elif [ "$section" = 4_1 ] && [ -n "$legacy" ]; then
				# Retain the old primary value as an editable recommendation while
				# archiving its implicit include; leave the policy disabled so
				# hardware/software flow offload remains available by default.
				ttl=$legacy
				if [ "$legacy" != 64 ] && [ "$legacy" != 65 ] ||
					[ "$(uci -q get qmodem_ttl.main.zbt_auto_ttl)" = 0 ]; then mode=manual; fi
			fi
		fi
		# A per-modem TTL entered outside the new UI is an explicit value.
		if uci -q get "qmodem_ttl.$section.ttl" >/dev/null; then mode=manual; fi
		if ! uci -q get "qmodem_ttl.$section" >/dev/null; then
			uci set "qmodem_ttl.$section=modem" || return 1
			changed=1
		fi
		for key in enable ttl mode; do
			if ! uci -q get "qmodem_ttl.$section.$key" >/dev/null; then
				value=$ttl; [ "$key" != enable ] || value=$enable
				[ "$key" != mode ] || value=$mode
				uci set "qmodem_ttl.$section.$key=$value" || return 1
				changed=1
			fi
		done
	done
	if ! uci -q get qmodem_ttl.main >/dev/null; then
		uci set qmodem_ttl.main=main || return 1
		changed=1
	fi
	for key in schema enable zbt_auto_ttl; do
		value=0; [ "$key" != schema ] || value=3
		if [ "$(uci -q get "qmodem_ttl.main.$key")" != "$value" ]; then
			uci set "qmodem_ttl.main.$key=$value" || return 1
			changed=1
		fi
	done
	[ "$changed" = 0 ] || uci commit qmodem_ttl || return 1
	# These two exact files belonged to the old TTL implementations. Move
	# them outside fw4's include glob, keeping even hand-edited copies.
	for file in 99-tether-ttl.nft 99-reset-ttl-from-br-lan.nft; do
		[ -e "$etc/nftables.d/$file" ] || continue
		mkdir -p "$etc/qmodem-ttl-backup" || return 1
		backup=$(mktemp "$etc/qmodem-ttl-backup/$file.XXXXXX") || return 1
		mv "$etc/nftables.d/$file" "$backup" || return 1
		logger -t qmodem_ttl "Archived legacy TTL rules at $backup; per-modem settings now own TTL"
	done
}
